Avoid query timeout in integration test
    Doing a CopyCassandra operation from beach (docker container) to a transient instance of Cassandra would generate error:
      java.io.IOException: Failed to write statements to delete_me.measured_value. The latest exception was
        Query timed out after PT2M
    Various settings for read/write request timeout didn't help.
    Setting the Spark master to local[2] instead of local[*] allows the test to pass.
    Working theory is that a threading issue loses the TableWriter close response and tweaking the number of cores avoids it.